Repository uoslife/client-meeting-season4, pull requests merged in 2024-04, with the labels that each got.

#76 [WEB-80] RangeSlider 관련 개선
  src/components/rangeSlider/RangeSlider.style.ts
  src/models/personal/data.ts
Labels: 👻 개선, 🚀 UI

#77 [WEB-93] 사업자 정보 추가
  src/pages/common/landingStep/Step.tsx
  src/types/icon.type.ts
Labels: 📄 페이지

#80 [WEB-97] axios reponse type 수정 및 response interceptor error 추가
  src/api/core/index.ts
  src/api/services/auth.ts
  src/api/services/meeting.ts
  src/api/services/payment.ts
  src/api/types/auth.type.ts
  src/api/types/index.ts
  src/main.tsx
  src/pages/common/univVerificationStep/ThirdPage.tsx
  vite.config.ts
Labels: ✨ API

#104 [WEB-99] 팅장 api 연결(/create)
  src/api/services/meeting.ts
  src/components/inputs/dropdownInput/DropdownInput.style.tsx
  src/pages/common/univVerificationStep/SecondPage.tsx
  src/pages/group/leader/createStep/SecondPage.tsx
  src/pages/group/leader/createStep/Step.tsx
  src/pages/group/leader/myInfomationStep/FirstPage.tsx
Labels: ✨ API

#114 feat[M4FE-27]: 3:3 팅원 페이지 성별 추가
  src/api/types/user.type.ts
  src/components/inputs/dropdownInput/DropdownInput.tsx
  src/models/group/data.ts
  src/models/group/data.type.ts
  src/models/group/validation.ts
  src/pages/group/member/myInformationStep/FirstPage.tsx
  src/pages/group/member/myInformationStep/SecondPage.tsx
  src/pages/group/member/myInformationStep/Step.tsx
Labels: 👥 미팅, 📄 페이지, UI

#103 [M4FE-14] 2차 QA UI
  src/api/services/meeting.ts
  src/components/applyInfo/DirectoryViewInfoList.tsx
  src/components/modal/applicationModal/ApplicationModal.style.tsx
  src/models/common/data.ts
  src/models/common/data.type.ts
  src/models/common/validation.ts
  src/pages/common/checkApplyInfoStep/Step.tsx
  src/pages/common/verifyForCheckAfterAleadyAppliedStep/FirstPage.tsx
  src/pages/common/verifyForCheckAfterAleadyAppliedStep/SecondPage.tsx
  src/pages/common/verifyForCheckAfterAleadyAppliedStep/Step.tsx
  src/pages/common/verifyForMatchingResultStep/FirstPage.tsx
  src/pages/common/verifyForMatchingResultStep/SecondPage.tsx
  src/pages/common/verifyForMatchingResultStep/Step.tsx
  src/pages/personal/myInformationStep/FifthPage.tsx
  src/pages/personal/myInformationStep/ForthPage.tsx
  src/pages/personal/myInformationStep/SixthPage.tsx
  src/pages/personal/myInformationStep/ThirdPage.tsx
  src/pages/personal/myPreferTypeStep/SecondPage.tsx
Labels: 📄 페이지, UI
