Repository uoslife/client-meeting-season4, pull requests merged in 2024-03, with the labels that each got.

#27 feat[WEB-38]: 전역값 localStorage 적용
  src/pages/common/univVerificationStep/FirstPage.tsx
  src/store/meeting/common.ts
  src/store/meeting/group.ts
  src/store/meeting/personal.ts
  src/types/apply.type.ts
Labels: 🥕 공통

#24 feat[WEB-35]: 공통 "미팅 종류 선택" 페이지 제작
  public/images/icons/arrow-black.svg
  src/components/buttons/checkbox/Checkbox.style.ts
  src/components/buttons/checkbox/Checkbox.tsx
  src/components/buttons/roundButton/RoundButton.tsx
  src/components/layout/Col.tsx
  src/pages/common/branchGatewayStep/FirstPage.tsx
  src/pages/common/branchGatewayStep/Step.tsx
  src/pages/group/myInfomationStep/Step.tsx
  src/routes/groupRoutes.tsx
  src/store/meeting/common.ts
  src/types/icon.type.ts
Labels: 🥕 공통, 📄 페이지

#26 feat[WEB-32] QuestionPageTemplate 리팩토링 / 우리 팅 정보 입력하기 페이지 제작
  src/components/questionPageTemplate/QuestionPageTemplate.tsx
  src/pages/group/groupInformationStep/FifthPage.tsx
  src/pages/group/groupInformationStep/ForthPage.tsx
  src/pages/group/groupInformationStep/SecondPage.tsx
  src/pages/group/groupInformationStep/SixthPage.tsx
  src/pages/group/groupInformationStep/Step.tsx
  src/pages/group/groupInformationStep/ThirdPapge.tsx
  src/pages/personal/myRomanceStep/FifthPage.tsx
  src/pages/personal/myRomanceStep/FirstPage.tsx
  src/pages/personal/myRomanceStep/ForthPage.tsx
  src/pages/personal/myRomanceStep/SecondPage.tsx
  src/pages/personal/myRomanceStep/ThirdPage.tsx
  src/store/meeting/common.ts
Labels: 👥 미팅, 📄 페이지, 👻 개선

#30 fix[WEB-44]: DropdownInput style 수정
  src/components/inputs/dropdownInput/DropdownInput.style.tsx
  src/components/inputs/dropdownInput/DropdownInput.tsx
Labels: 🥕 공통, 👻 개선

#22 feat[WEB-31]: 공통 "대학 이메일 인증" 페이지 제작
  src/components/inputs/textInput/TextInput.tsx
  src/pages/common/univVerificationStep/SecondPage.tsx
Labels: 🥕 공통, 📄 페이지

#31 feat[WEB-43]: 3:3 "미팅 참여 역할 선택" 페이지 제작
  src/pages/common/branchGatewayStep/FirstPage.tsx
  src/pages/common/branchGatewayStep/Step.tsx
  src/pages/common/univVerificationStep/FirstPage.tsx
  src/pages/group/groupRoleSelectStep/FirstPage.tsx
  src/pages/group/groupRoleSelectStep/Step.tsx
  src/store/meeting/group.ts
Labels: 👥 미팅, 📄 페이지

#38 feat[WEB-52]: "신청완료" 페이지 구현
  public/images/common/finish-apply-step-img.png
  public/images/icons/next-icon-white.svg
  src/components/modal/participationModal/ParticipationModal.style.tsx
  src/components/modal/participationModal/ParticipationModal.tsx
  src/pages/common/finishApplyStep/FirstPage.tsx
  src/pages/common/finishApplyStep/Step.tsx
Labels: 📄 페이지

#34 feat[WEB-47]: 1:1 "01. 나의 정보 입력하기" 페이지 구현
  src/components/buttons/interestButton/InterestButton.style.tsx
  src/components/buttons/interestButton/InterestButton.tsx
  src/components/buttons/mbtiButton/MbtiButton.style.tsx
  src/components/buttons/mbtiButton/MbtiButton.tsx
  src/components/typography/Text.tsx
  src/constants/index.ts
  src/hooks/useToggleSelect.tsx
  src/pages/personal/myInformationStep/FifthPage.tsx
  src/pages/personal/myInformationStep/FirstPage.tsx
  src/pages/personal/myInformationStep/ForthPage.tsx
  src/pages/personal/myInformationStep/SecondPage.tsx
  src/pages/personal/myInformationStep/SixthPage.tsx
  src/pages/personal/myInformationStep/Step.tsx
  src/pages/personal/myInformationStep/ThirdPage.tsx
  src/pages/personal/myInformationStep/ThirdPapge.tsx
  src/routes/personalRoutes.tsx
  src/store/meeting/common.ts
  src/store/meeting/personal.ts
Labels: 💁 소개팅, 📄 페이지

#42 feat[WEB-57]: 3:3 "팅 만들기" 스텝 제작
  public/images/icons/checkCircle-active.svg
  public/images/icons/checkCircle-inactive.svg
  public/images/icons/human-circle.svg
  src/components/inputs/textInput/TextInput.tsx
  src/pages/group/groupCreateStep/FirstPage.tsx
  src/pages/group/groupCreateStep/SecondPage.tsx
  src/pages/group/groupCreateStep/Step.tsx
  src/types/icon.type.ts
Labels: 👥 미팅, 📄 페이지

#48 feat[WEB-59]: 공통 '메인 포스터' 페이지 제작
  package.json
  public/images/icons/instagram.svg
  public/images/icons/kakaotalk.svg
  public/images/icons/musicNote-red.svg
  public/images/icons/share.svg
  public/images/main/poster1.png
  public/images/main/poster2.png
  src/components/questionPageTemplate/QuestionLabel.tsx
  src/components/questionPageTemplate/QuestionPageTemplate.tsx
  src/constants/index.ts
  src/pages/common/landingStep/Step.tsx
  src/types/icon.type.ts
  yarn.lock
Labels: 🥕 공통, 📄 페이지

#45 feat[WEB-63]: “개인정보 처리 방침” 페이지 제작
  public/fonts/GothicA1-Bold.ttf
  src/App.tsx
  src/components/layout/page/header/Header.tsx
  src/components/typography/Text.tsx
  src/pages/common/branchGatewayStep/FirstPage.tsx
  src/pages/common/privacyPolicyStep/FirstPage.tsx
  src/pages/common/privacyPolicyStep/Step.tsx
  src/styles/reset.ts
  src/styles/typographies.ts
Labels: 🥕 공통, 📄 페이지, 👻 개선

#44 feat[WEB-62]: "경희대·한국외대 구성원 인증" 서약 페이지 제작
  src/components/buttons/roundButton/RoundButton.tsx
  src/pages/common/univVerificationStep/FirstPage.tsx
  src/pages/common/univVerificationStep/SecondPage.tsx
  src/pages/common/univVerificationStep/Step.tsx
  src/pages/common/univVerificationStep/ThirdPage.tsx
Labels: 🥕 공통, 📄 페이지, 👻 개선

#43 feat[WEB-61]: msw 환경설정
  package.json
  src/main.tsx
  src/mocks/handlers.ts
  src/mocks/worker.ts
  yarn.lock
Labels: 🥕 공통

#52 feat[WEB-69]: msw 기반 Axios api 추상화 작업
  package.json
  src/api/core/index.ts
  src/api/index.ts
  src/api/services/auth.ts
  src/api/services/meeting.ts
  src/api/services/payment.ts
  src/api/types/auth.type.ts
  src/api/types/index.ts
  src/api/types/payment.type.ts
  src/api/types/user.type.ts
  src/mocks/handlers.ts
  src/pages/common/univVerificationStep/ThirdPage.tsx
  vite.config.ts
  yarn.lock
Labels: 🥕 공통

#51 feat[WEB-65]: 시대팅 이용 서약 페이지 및 팅원 완료 페이지 제작
  src/components/inputs/textInput/TextInput.style.tsx
  src/pages/common/useAgreementStep/FirstPage.tsx
  src/pages/common/useAgreementStep/Step.tsx
  src/pages/group/teamMemberFinishApplyStep/FirstPage.tsx
  src/pages/group/teamMemberFinishApplyStep/Step.tsx
  src/routes/commonRoutes.tsx
  src/routes/groupRoutes.tsx
Labels: 📄 페이지

#56 feat[WEB-66]: useStepToGoBack 완성과 시범 적용
  src/hooks/useFunnel.tsx
  src/hooks/useStepToGoBack.ts
  src/pages/common/branchGatewayStep/Step.tsx
  src/pages/common/univVerificationStep/Step.tsx
  src/pages/personal/myInformationStep/Step.tsx
Labels: 🥕 공통, 👻 개선

#58 feat[WEB-68]: 포트원 결제모듈 부착
  index.html
  public/images/icons/payment-loading.svg
  public/images/uoslifeLogo-loadingSpinner.webp
  src/constants/payment.ts
  src/pages/common/paymentResultStep/LoadingPage.tsx
  src/pages/common/paymentResultStep/Step.tsx
  src/pages/common/paymentStep/FirstPage.tsx
  src/pages/common/paymentStep/PaymentPage.tsx
  src/pages/common/paymentStep/Step.tsx
  src/types/icon.type.ts
  src/types/payment.type.ts
Labels: 🥕 공통, 📄 페이지

#60 [WEB-39] 1차 QA
  public/images/common/checkApplyInfoStep/HUFS.png
  public/images/common/checkApplyInfoStep/KHU.png
  public/images/common/checkApplyInfoStep/UOS.png
  public/images/common/checkApplyInfoStep/group.png
  public/images/common/finish-apply-step-img.png
  public/images/group/groupInformationStep/2.png
  public/images/group/groupInformationStep/3.png
  public/images/group/groupInformationStep/4.png
  public/images/group/groupInformationStep/5.png
  public/images/icons/next-icon-black.svg
  public/images/icons/univSelection/KHU.png
  public/images/main/poster1.png
  public/images/main/poster2.png
  public/images/main/subtitle.png
  public/images/main/title.png
  public/images/personal/myRomanceStep/3.png
  public/images/personal/myRomanceStep/5.png
  src/api/types/user.type.ts
  src/components/applyInfo/DirectoryViewInfoList.tsx
  src/components/applyInfo/Profile.tsx
  src/components/modal/applicationModal/ApplicationModal.style.tsx
  src/hooks/useGroupEntireValue.ts
  src/hooks/usePersonalEntireValue.ts
  src/mocks/handlers.ts
  src/models/funnel/index.ts
  src/pages/common/applyPledgeStep/Step.tsx
  src/pages/common/branchGatewayStep/Step.tsx
  src/pages/common/checkAfterAleadyAppliedStep/Step.tsx
  src/pages/common/checkApplyInfoStep/FirstPage.tsx
  src/pages/common/checkApplyInfoStep/Step.tsx
  src/pages/common/finishApplyStep/Step.tsx
  src/pages/common/landingStep/Step.tsx
  src/pages/common/univVerificationStep/FirstPage.tsx
  src/pages/common/verifyForCheckAfterAleadyAppliedStep/Step.tsx
  src/pages/group/leader/groupInformationStep/FifthPage.tsx
  src/pages/group/leader/groupInformationStep/ForthPage.tsx
  src/pages/group/leader/groupInformationStep/SecondPage.tsx
  src/pages/group/leader/groupInformationStep/ThirdPage.tsx
  src/pages/group/leader/pledgeStep/Step.tsx
  src/pages/group/leader/preferStep/Step.tsx
  src/pages/group/teamMemberFinishApplyStep/FirstPage.tsx
  src/pages/group/teamMemberFinishApplyStep/Step.tsx
  src/routes/commonRoutes.tsx
  src/store/meeting/common.ts
  src/store/meeting/group.ts
  src/store/meeting/index.ts
  src/store/meeting/personal.ts
Labels: 👥 미팅, 💁 소개팅, 🥕 공통, 📄 페이지, 👻 개선

#59 feat[WEB-75]: msw 환경 api 결제 모듈 부착 및 결제 취소 디바이스별 대응
  .gitignore
  index.html
  package.json
  src/api/services/payment.ts
  src/api/types/payment.type.ts
  src/components/layout/page/PageLayout.tsx
  src/mocks/handlers.ts
  src/pages/common/paymentResultStep/Step.tsx
  src/pages/common/paymentStep/PaymentPage.tsx
  src/pages/common/paymentStep/Step.tsx
  src/types/payment.type.ts
  yarn.lock
Labels: 🥕 공통, 📄 페이지

#64 fix[WEB-78]: mbti type string[] -> string으로 변경
  src/models/options.ts
  src/models/personal/data.ts
  src/models/personal/validation.ts
  src/pages/personal/myInformationStep/FifthPage.tsx
  src/pages/personal/myPreferTypeStep/ForthPage.tsx
Labels: 💁 소개팅, 📄 페이지, 👻 개선

#65 fix[WEB-79]: DropdownInput 초기값 null로 수정
  src/models/group/data.ts
  src/models/personal/data.ts
Labels: 👥 미팅, 💁 소개팅, 📄 페이지, 👻 개선

#66 feat[WEB-86]: 포트원 리다이렉트 url 변경 및 스크롤바 제거
  src/pages/common/paymentStep/PaymentPage.tsx
  src/styles/reset.ts
Labels: 🥕 공통, 🚀 UI

#68 feat[WEB-88]: 변경된 디자인 반영(* 본문 개요 참조)
  public/images/icons/footerButton-left-able.svg
  public/images/icons/footerButton-right-able.svg
  public/images/icons/footerButton-right-disabled.svg
  public/images/main/mainTextLogo.png
  public/images/main/subtitle.png
  public/images/main/title.png
  src/components/layout/page/footer/Footer.tsx
  src/pages/common/landingStep/Step.tsx
  src/pages/group/leader/myInfomationStep/SecondPage.tsx
  src/pages/group/leader/pledgeStep/FirstPage.tsx
  src/pages/personal/myInformationStep/FifthPage.tsx
  src/pages/personal/myInformationStep/SecondPage.tsx
  src/pages/personal/myPreferTypeStep/ThirdPage.tsx
  src/types/icon.type.ts
Labels: 👥 미팅, 💁 소개팅

#67 feat[WEB-87]: DropDownInput 컴포넌트 close 애니메이션 추가
  src/components/inputs/dropdownInput/DropdownInput.style.tsx
  src/components/inputs/dropdownInput/DropdownInput.tsx
  src/components/modal/participationModal/ParticipationModal.tsx
Labels: 🥕 공통, 👻 개선, 🚀 UI

#71 feat[WEB-90]: 시대팅 가격 정책 반영
  src/pages/common/paymentStep/PaymentPage.tsx
Labels: 🥕 공통, 📄 페이지

#69 feat[WEB-89]: NotFound 페이지 제작
  public/images/not-found.png
  src/pages/common/notFound/NotFoundPage.tsx
  src/routes/commonRoutes.tsx
  src/styles/colors.ts
Labels: 🥕 공통, 📄 페이지

#72 fix[WEB-92]: 1:1 "선호하는 상대 정보 입력하기" 페이지 종교 버튼 수정
  src/models/options.ts
  src/pages/personal/myPreferTypeStep/SecondPage.tsx
Labels: 💁 소개팅, 📄 페이지, 👻 개선

#73 fix[WEB-85]: 시대팅 이용 서약 페이지 check 범위 수정 및 align left 설정
  src/components/pledgeItem/PledgeItem.tsx
Labels: 🥕 공통, 📄 페이지, 👻 개선

#75 feat[WEB-84]: 매칭결과 페이지를 위한 API 작업 등
  src/api/services/meeting.ts
  src/api/types/user.type.ts
  src/components/applyInfo/ApplyInfo.tsx
  src/components/applyInfo/ApplyInfoProfile.tsx
  src/components/applyInfo/CheckCards.tsx
  src/components/applyInfo/CheckPageDoubleCards.tsx
  src/components/applyInfo/CheckPageTopSayings.tsx
  src/components/applyInfo/MatchingCard.tsx
  src/components/applyInfo/MatchingFailedContent.tsx
  src/components/applyInfo/MatchingSuccessfulContent.tsx
  src/mocks/handlers.ts
  src/pages/common/checkAfterAleadyAppliedStep/Step.tsx
  src/pages/common/checkApplyInfoStep/FirstPage.tsx
  src/pages/common/checkApplyInfoStep/temp.tsx
  src/pages/common/landingStep/Step.tsx
  src/pages/common/matchingStep/Step.tsx
  src/pages/common/matchingSuccessfulStep/Step.tsx
  src/routes/commonRoutes.tsx
  src/utils/meetingInfo/constants.ts
  src/utils/meetingInfo/index.ts
  src/utils/meetingInfo/label-getters.ts
Labels: 🥕 공통, 📄 페이지, ✨ API
