Repository uoslife/client-meeting-season4, pull requests merged in 2024-02, with the labels that each got.

#1 feat(WEB-1): Button 공통 컴포넌트 제작
  src/compents/buttons/Button.style.tsx
  src/compents/buttons/Button.tsx
  src/hooks/useSingleSelect.tsx
  src/hooks/useToggleSelect.tsx
Labels: 🥕 공통

#3 feat(WEB-4): Text 컴포넌트 제작
  public/fonts/GothicA1-Regular.ttf
  public/fonts/NeoDunggeunmoPro-Regular.ttf
  public/fonts/PFstardust.ttf
  public/fonts/Pretendard-Regular.ttf
  public/images/vite.svg
  public/vite.svg
  src/compents/typography/Text.tsx
  src/styles/reset.ts
  src/styles/typographies.ts
  src/types/style.type.ts
Labels: 🥕 공통

#2 feat: Input 공통 컴포넌트 제작
  src/compents/inputs/TextInput.style.tsx
  src/compents/inputs/TextInput.tsx
  src/hooks/useInput.tsx
Labels: 🥕 공통

#5 feat(WEB-15): Icon 컴포넌트 작성
  public/images/icons/vite.svg
  src/components/buttons/iconButton/IconButton.style.tsx
  src/components/buttons/iconButton/IconButton.tsx
  src/components/buttons/roundButton/RoundButton.style.tsx
  src/components/buttons/roundButton/RoundButton.tsx
  src/components/layout/Col.tsx
  src/components/layout/Pad.tsx
  src/components/layout/Row.tsx
  src/components/typography/Text.tsx
  src/types/icon.type.ts
Labels: 🥕 공통

#10 feat(WEB-5): 페이지네이션 로직 훅(useFunnel) 제작
  package.json
  src/App.tsx
  src/hooks/useFunnel.tsx
  src/pages/personal/myInformationStep/FifthPage.tsx
  src/pages/personal/myInformationStep/FirstPage.tsx
  src/pages/personal/myInformationStep/ForthPage.tsx
  src/pages/personal/myInformationStep/SecondePage.tsx
  src/pages/personal/myInformationStep/SixthPage.tsx
  src/pages/personal/myInformationStep/ThirdPapge.tsx
  src/pages/personal/myInformationStep/index.tsx
  src/routes/commonRoutes.tsx
  src/routes/groupRoutes.tsx
  src/routes/index.tsx
  src/routes/personalRoutes.tsx
  yarn.lock
Labels: 🥕 공통

#11 feat(WEB-7): Footer 하단 공통 컴포넌트 제작.
  public/images/icons/footerButton-able.svg
  public/images/icons/footerButton-disabled.svg
  src/components/buttons/checkbox/Checkbox.style.ts
  src/components/buttons/checkbox/Checkbox.tsx
  src/components/inputs/TextInput.style.tsx
  src/components/inputs/TextInput.tsx
  src/components/layout/Row.tsx
  src/components/layout/footer/Footer.style.tsx
  src/components/layout/footer/Footer.tsx
  src/hooks/useFunnel.tsx
  src/pages/personal/myInformationStep/FifthPage.tsx
  src/pages/personal/myInformationStep/FirstPage.tsx
  src/pages/personal/myInformationStep/ForthPage.tsx
  src/pages/personal/myInformationStep/SecondPage.tsx
  src/pages/personal/myInformationStep/SecondePage.tsx
  src/pages/personal/myInformationStep/SixthPage.tsx
  src/pages/personal/myInformationStep/ThirdPapge.tsx
  src/pages/personal/myInformationStep/index.tsx
  src/types/icon.type.ts
  src/types/page.type.ts
Labels: 🥕 공통

#8 feat(WEB-19): TextInput에 xButton 아이콘 추가
  public/images/icons/clearButton.svg
  src/components/checkbox/Checkbox.style.ts
  src/components/checkbox/Checkbox.tsx
  src/components/inputs/TextInput.style.tsx
  src/components/inputs/TextInput.tsx
  src/types/icon.type.ts
Labels: 🥕 공통

#7 feat(WEB-16): AnimalButton 컴포넌트 제작
  public/images/icons/animals/bear.png
  public/images/icons/animals/cat.png
  public/images/icons/animals/chick.png
  public/images/icons/animals/dinosaur.png
  public/images/icons/animals/dog.png
  public/images/icons/animals/fox.png
  public/images/icons/animals/hamster.png
  public/images/icons/animals/monkey.png
  public/images/icons/animals/rabbit.png
  public/images/icons/check.svg
  src/components/buttons/animalButton/AnimalButton.style.tsx
  src/components/buttons/animalButton/AnimalButton.tsx
  src/components/layout/gridWrapper/GridWrapper.style.tsx
  src/components/layout/gridWrapper/GridWrapper.tsx
  src/constants/index.ts
  src/hooks/useToggleSelect.tsx
  src/types/icon.type.ts
Labels: 🥕 공통

#12 feat[WEB-6]: Header 상단 공통 컴포넌트 제작
  public/images/icons/headerButton-backArrow.svg
  public/images/icons/headerButton-home.svg
  src/App.tsx
  src/components/layout/footer/Footer.tsx
  src/components/layout/header/Header.style.tsx
  src/components/layout/header/Header.tsx
  src/pages/personal/myInformationStep/FirstPage.tsx
  src/pages/personal/myInformationStep/index.tsx
  src/styles/GlobalStyle.tsx
  src/styles/reset.ts
  src/styles/typographies.ts
  src/types/icon.type.ts
Labels: 🥕 공통

#9 feat[WEB-13]: ConnectedTwoCards 컴포넌트 구현, BodyContainer의 bodyCardType = "DOUBLE" case 구현
  public/images/dashed-line-bg-white.png
  src/components/card/Card.tsx
  src/components/card/connectedTwoCards/CardConnector.tsx
  src/components/card/connectedTwoCards/ConnectedTwoCards.tsx
  src/components/layout/bodyContainer/BodyCard.tsx
  src/components/layout/bodyContainer/BodyCardWrapper.tsx
  src/components/layout/bodyContainer/BodyContainer.tsx
  src/components/layout/bodyContainer/BodyContainer.type.ts
Labels: 🥕 공통

#14 feat[WEB-23]: RangeSlider 컴포넌트와 useRangeState 구현
  package.json
  src/components/rangeSlider/RangeSlider.style.ts
  src/components/rangeSlider/RangeSlider.tsx
  src/components/rangeSlider/RangeSliderBackground.tsx
  src/components/rangeSlider/RangeSliderHandle.tsx
  src/components/rangeSlider/RangeSliderMarkText.tsx
  src/hooks/useRangeState.tsx
  src/styles/colors.ts
  yarn.lock
Labels: 🥕 공통

#15 feat[WEB-27]: 레이아웃 컴포넌트, 폴더구조 대폭 수정
  src/App.tsx
  src/components/card/Card.tsx
  src/components/card/connectedTwoCards/CardConnector.tsx
  src/components/card/connectedTwoCards/ConnectedTwoCards.tsx
  src/components/layout/bodyContainer/BodyCard.tsx
  src/components/layout/bodyContainer/BodyCardWrapper.tsx
  src/components/layout/bodyContainer/BodyContainer.tsx
  src/components/layout/bodyContainer/BodyContainer.type.ts
  src/components/layout/footer/Footer.style.tsx
  src/components/layout/footer/Footer.tsx
  src/components/layout/page/PageLayout.tsx
  src/components/layout/page/body/Body.style.ts
  src/components/layout/page/body/Body.type.ts
  src/components/layout/page/body/DoubleCardBody.tsx
  src/components/layout/page/body/SingleCardBody.tsx
  src/components/layout/page/footer/Footer.style.ts
  src/components/layout/page/footer/Footer.tsx
  src/components/layout/page/header/Header.style.ts
  src/components/layout/page/header/Header.tsx
  src/pages/personal/myInformationStep/index.tsx
Labels: 🥕 공통

#19 feat(WEB-28): Funnel 예시 페이지 제작
  package.json
  public/images/icons/univSelection/HUFS.png
  public/images/icons/univSelection/KHU.png
  src/App.tsx
  src/components/card/Card.tsx
  src/components/layout/footer/Footer.tsx
  src/components/layout/page/body/Body.style.ts
  src/components/layout/page/footer/Footer.style.ts
  src/components/layout/page/footer/Footer.tsx
  src/hooks/useFunnel.tsx
  src/pages/common/applyPledgeStep/FirstPage.tsx
  src/pages/common/applyPledgeStep/Step.tsx
  src/pages/common/branchGatewayStep/FirstPage.tsx
  src/pages/common/branchGatewayStep/Step.tsx
  src/pages/common/checkApplyInfoStep/FirstPage.tsx
  src/pages/common/checkApplyInfoStep/Step.tsx
  src/pages/common/finishApplyStep/FirstPage.tsx
  src/pages/common/finishApplyStep/Step.tsx
  src/pages/common/landingStep/Step.tsx
  src/pages/common/paymentStep/FirstPage.tsx
  src/pages/common/paymentStep/Step.tsx
  src/pages/common/privacyPolicyStep /FirstPage.tsx
  src/pages/common/privacyPolicyStep /Step.tsx
  src/pages/common/univVerificationStep/FirstPage.tsx
  src/pages/common/univVerificationStep/Step.tsx
  src/pages/group/groupCreateStep/Step.tsx
  src/pages/group/groupInformationStep/Step.tsx
  src/pages/group/groupParticipateStep/FirstPage.tsx
  src/pages/group/groupParticipateStep/Step.tsx
  src/pages/group/groupPreferStep/FirstPage.tsx
  src/pages/group/groupPreferStep/Step.tsx
  src/pages/group/groupRoleSelectStep/FirstPage.tsx
  src/pages/group/groupRoleSelectStep/Step.tsx
  src/pages/group/myInfomationStep/Step.tsx
  src/pages/personal/myInformationStep/Step.tsx
  src/pages/personal/myInformationStep/index.tsx
  src/pages/personal/myPreferTypeStep/Step.tsx
  src/pages/personal/myRomanceStep/Step.tsx
  src/routes/commonRoutes.tsx
  src/store/funnel/index.ts
  src/store/meeting/common.ts
  src/store/meeting/group.ts
  src/store/meeting/personal.ts
  src/types/icon.type.ts
  yarn.lock
Labels: 🥕 공통, 📄 페이지

#16 feat(WEB-17): DropdownInput 공통 컴포넌트 제작
  public/images/icons/dropdown.svg
  src/components/inputs/dropdownInput/DropdownInput.style.tsx
  src/components/inputs/dropdownInput/DropdownInput.tsx
  src/components/inputs/textInput/TextInput.style.tsx
  src/components/inputs/textInput/TextInput.tsx
  src/styles/colors.ts
  src/types/icon.type.ts
Labels: 🥕 공통

#20 fix(WEB-30): atom 구조 변경
  src/hooks/useGroupEntireValue.ts
  src/hooks/usePersonalEntireValue.ts
  src/store/meeting/common.ts
  src/store/meeting/group.ts
  src/store/meeting/personal.ts
  src/types/apply.type.ts
Labels: 🥕 공통, 👻 개선

#17 feat(WEB-26): ParticipationModal 컴포넌트 제작
  public/images/icons/participationModal-human.svg
  src/components/buttons/roundButton/RoundButton.style.tsx
  src/components/buttons/roundButton/RoundButton.tsx
  src/components/modal/participationModal/ParticipationModal.style.tsx
  src/components/modal/participationModal/ParticipationModal.tsx
  src/styles/colors.ts
  src/types/icon.type.ts
Labels: 🥕 공통

#21 feat[WEB-29]: 1:1 "02. 나의 연애 스타일 알아보기" 페이지 제작
  public/images/personal/myRomanceStep/1.png
  public/images/personal/myRomanceStep/2.png
  public/images/personal/myRomanceStep/3.png
  public/images/personal/myRomanceStep/4.png
  public/images/personal/myRomanceStep/5.png
  src/components/questionPageTemplate/QuestionLabel.tsx
  src/components/questionPageTemplate/QuestionPageTemplate.tsx
  src/pages/personal/myRomanceStep/FifthPage.tsx
  src/pages/personal/myRomanceStep/FirstPage.tsx
  src/pages/personal/myRomanceStep/ForthPage.tsx
  src/pages/personal/myRomanceStep/SecondPage.tsx
  src/pages/personal/myRomanceStep/Step.tsx
  src/pages/personal/myRomanceStep/ThirdPage.tsx
  src/styles/colors.ts
  src/types/apply.type.ts
Labels: 👥 미팅, 📄 페이지
